version: '3.7'

services:
    frontend:
        stdin_open: true
        build:
          context: ./geo_front
          dockerfile: Dockerfile
        expose:
          - 3000
        ports:
          - "3000:3000"
        depends_on: [backend]
    backend:
        container_name: simulator
        build: 
          context: ./simulator
          dockerfile: Dockerfile
        expose:
          - 5000
        ports:
          - 5000:5000
